// Database types — Convex
// All type definitions are auto-generated by Convex in convex/_generated/dataModel.
// This file is kept for reference and any custom type aliases.

export type OrderStatus = "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled";
export type PaymentStatus = "pending" | "paid" | "failed" | "refunded";
export type UserRole = "user" | "admin";
